CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY DEFAULT (floor(random() * 1000000000000)::BIGINT),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);