name: Build and Push Docker Images on Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push frontend image
        id: push-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./fe
          file: ./fe/Dockerfile
          push: true
          tags: |
            gnmrschnzs/donkeyhorse-fe:${{ steps.extract_tag.outputs.tag }}
            gnmrschnzs/donkeyhorse-fe:latest
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

      - name: Build and push backend image
        id: push-backend
        uses: docker/build-push-action@v5
        with:
          context: ./be
          file: ./be/Dockerfile
          push: true
          tags: |
            gnmrschnzs/donkeyhorse-be:${{ steps.extract_tag.outputs.tag }}
            gnmrschnzs/donkeyhorse-be:latest
