name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend image
        id: push-frontend
        uses: docker/build-push-action@v2
        with:
          context: ./fe
          file: ./fe/Dockerfile
          push: true
          tags: gnmrschnzs/donkeyhorse-fe:${{ github.ref_name }}
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

      - name: Build and push backend image
        id: push-backend
        uses: docker/build-push-action@v2
        with:
          context: ./be
          file: ./be/Dockerfile
          push: true
          tags: gnmrschnzs/donkeyhorse-be:${{ github.ref_name }}
